version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config: 
      config: .eslintrc.json
    checks:
      # indent rules on codeclimate seem to be different from
      # the local ones - probably because cc uses an older version
      # of eslint
      indent:
        enabled: false
exclude_patterns:
  - ".github/"
  - "test/"
  - "tmp/"
  - "utl/"
  - "**/node_modules/"